### ISSUE TITLE
v1.6 To-Do

### ISSUE THREAD

**Issue by AhmadHrb** [PocketInc/Pocket-Browser#1]
# Pocket Browser V1.6:

- [x] All Done.

## Bugs:

- [x] **Window.Open** cannot open "blank" pages.
- [x] Fix errors.

## Features:

- [x] Auto Updater.
- [x] System Pages loading in Browser.
- [x] Download Manager.
- [x] Improve Notifications System.
- [x] Start Page.
- [x] Design Changes.
- [x] Extensions Pages.
- [x] Cloud Sync
- [x] Error reporting.
- [x] Bookmarks.

**Contributions are welcome!**

Pocket Team.

**Comment by AhmadHrb** [comment]
**Pocket Browser V1.5** is released!
